#	@(#)Makefile	8.1 (Berkeley) 7/19/93
# $FreeBSD: head/usr.bin/rsh/Makefile 315170 2017-03-12 18:58:44Z imp $

PROG=	rsh
#CFLAGS+=-I${SRCTOP}/libexec/rlogind

PACKAGE=rcmds

BINOWN=	root
BINMODE=4555
BINDIR?=${PREFIX}/bin

.include <bsd.prog.mk>
